### ISSUE TITLE
City of Pittsburgh, PA is duplicated in the dataset (1965-1980) 

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/MGG-Data#45]
In the year of 1989, a typo (an extra space) created a separate value for the city of Pittsburgh in the controlled vocabulary.
Might need to check other years in the dataset to see if the duplicate reoccurs.

**Comment by regan008** [comment]
check 1990-1996 and make changes in the original data then redownload clear into mgg-data/2-OrigData
