### ISSUE TITLE
Check for data entries assigned wrong cities and states (1989-1996)

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/MGG-Data#49]
Some border cities like St Louis, MO, Kansas City, KS, Davenport, IA, Rock Island, IL, and others were listed under one city and described as part of another city in the guides. 

* Check to ensure that the city/state listed in each entry's description is the actual city/state of said entry;
* Fix _city_ and _state_ columns to reflect precise location;
* Keep city/state information in the _description_ column (**NOT** in the _streetaddress_ column)

**Comment by regan008** [comment]
Fix if time allows
