### ISSUE TITLE
Duplicate data entries in 1987, 1988, and 1989

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/MGG-Data#51]
Many duplicate entries especially in 1988, with occasional occurrence in 1987 and 1989. 

Realized some locations were divided into two separate entries during data transcription. I.e.:

<b> Mercantile Saloon (Some OC ) (L iq u o r) ★
20th & 'L' Sts. </b>

Transcription:
<i>title:</i> Mercantile Saloon
<i>streetaddress:</i> 'L' Sts.

<i>title:</i> Mercantile Saloon
<i>streetaddress:</i> 20th

Correction: 

<i>title:</i> Mercantile Saloon
<i>streetaddress:</i> 20th & 'L' Sts.

I'm fixing them as I go through unclear addresses, but it might be worth checking back later.

**Comment by regan008** [comment]
Luc, can you add this to the data integrity checklist?

**Comment by regan008** [comment]
Will close and revisit later if time allows.
