### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by radiatoryang** [MappingtheGayGuides/MGG-Data#53]
Hello, sorry to bother you. I'm interested in using this data for my own visualizations and gay history projects. Is there a license for this data? Your site implies everything is Creative Commons CC-BY 4.0 https://creativecommons.org/licenses/by/4.0/ but this data repo itself doesn't have a license. Would it also be under CC-BY 4.0? Anyway, thanks for all your work and research into this!

**Comment by regan008** [comment]
Hi @radiatoryang - Yes thats correct, the data is licenced under a CC-BY 4.0 license. You are welcome to use it for your own projects we just ask that you cite us as follows: 
Mapping the Gay Guides, Amanda Regan and Eric Gonzaba, (2019-): http:// [www.mappingthegayguides.org](https://www.mappingthegayguides.org/).
