### ISSUE TITLE
1990s bases with multiple data entry errors

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/MGG-Data#54]
* Reminder to re-download the 1991 clear data **AFTER** fixing all the data entry errors and this issue is officially closed.

Many data entries in 1991 had cities and states mixed up during transcription. The confusion of cities between Indiana and Illinois has been fixed in both unclear and clear data bases. 

The following cities mistakenly listed under Minnesota (MN) **still need revision in the clear 1991 data base**: 

- Batesville, MS
- Biloxi, MS
- Columbia, MO
- Forest, MS
- Hattiesburg, MS
- Hernando, MS
- Huntsville, MO
- Jackson, MS
- Joplin, MO
- Kansas City, MO
- Meridian, MS
- Morton, MS
- Oxford, MS
- Pascagoula, MS
- Springfield, MO
- St. Joseph, MO
- St. Louis, MO
- Vicksburg, MS 
- Moberly, MO
- Magee, MS
- New Madrid, MO
- Gulfport, MS

New data entry errors that require revision in the clear 1991 data will be added to this Issue in follow-up comments.

**Comment by lukeave** [comment]
- **Grand Island, NE** is listed under Montana (MT) in 1992.
- **Kearney, NE** is listed under Montana (MT) in 1992.
- **Lincoln, NE** is listed under Montana (MT) in 1992.
- **Norfolk, NE** is listed under Montana (MT) in 1992.
- **Omaha, NE** is listed under Montana (MT) in 1992.

**Comment by lukeave** [comment]
* **Chattanooga, TN** is listed under South Dakota (SD) in 1995.
* **Clarksville, TN** is listed under South Dakota (SD) in 1995.
* **Jackson, TN** is listed under South Dakota (SD) in 1995.
* **Johnson City, TN** is listed under South Dakota (SD) in 1995.
* **Knoxville, TN** is listed under South Dakota (SD) in 1995.
* **Liberty, TN** is listed under South Dakota (SD) in 1995.
* **Memphis, TN** is listed under South Dakota (SD) in 1995.
* **Murpheesboro, TN** is listed under South Dakota (SD) in 1995.
* **Nashville, TN** is listed under South Dakota (SD) in 1995.
* **Kingsport, TN** is listed under South Dakota (SD) in 1995. 
* **Haley, TN** is listed under South Dakota (SD) in 1995.
* **Saltillo, TN** is listed under South Dakota (SD) in 1995.
* **Gatlinburg, TN** is listed under South Dakota (SD) in 1995.
* **Rogersville, TN** is listed under South Dakota (SD) in 1995.
*  **Greeneville, TN** is listed under South Dakota (SD) in 1995.

**Comment by regan008** [comment]
Luc, could you fix these in the main bases and then filter by clear data and redownload each csv? They should go in 2-OrigDataforGeocoding.

**Comment by lukeave** [comment]
update: 1991 clear data fixed

**Comment by lukeave** [comment]
update: 1992 clear data fixed

**Comment by lukeave** [comment]
update: 1995 clear data fixed

**Comment by lukeave** [comment]
update: Minnesota/St. Paul listings standardized throughout 1990-1996 data
