### ISSUE TITLE
1998 (Clemson) Base - Missing pages

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/MGG-Data#76]
For my own record, I'll add here the pages of the guide that I can't find among the student transcriptions (guide's actual pages; NOT pdf's).

- pp. 33-36.
- p. 329 
- pp. 337 onwards

**Comment by lukeave** [comment]
Transcription of missing pages 33-36 and 329 complete.

**Comment by lukeave** [comment]
Revisit this. @regan008

**Comment by regan008** [comment]
Missing pages are complete, right @lukeave? Can we close this and I'll create a new issue for the Spring 24 new entries?

**Comment by lukeave** [comment]
Yes, I’ve transcribed those missing pages! @regan008

**Comment by lukeave** [comment]
More missing pages in 1998... 

PDF pages: 445-454

First entry: "Windsor Court", Provincetown, MA
Last entry: "Cherie Inn", Grand Rapids, MI

**Comment by lukeave** [comment]
@tmmarks completed these. Thanks Taylor!
