### ISSUE TITLE
Finish transcription for 1998

### ISSUE THREAD

**Issue by regan008** [MappingtheGayGuides/MGG-Data#91]
Transcription for remaining data in 1998. PDF pages 573-822. Contiguous US (us+territories) only. Should go in the "MGG 1998 Data (Clemson)" Base in Airtable. There is a sheet called "1998 - Remaining Entries (Taylor)" for you to use.

**Comment by regan008** [comment]
@tmmarks I think you've done MGG transcription before, but I can't recall for sure. If not send me an email and we can talk about it before you get started. Can also talk further with @lukeave at the project kick off in a couple weeks.

**Comment by tmmarks** [comment]
The remaining transcription for 1998 is officially done! I went through and cleaned it up, but if anyone sees anything that needs editing, let me know!

**Comment by lukeave** [comment]
Thanks @tmmarks! I went ahead and finished cleaning a couple of small things too -- fantastic job!
